# Generated by Django 4.2.2 on 2024-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20240602_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='mode',
            field=models.CharField(max_length=100),
        ),
    ]
