# Generated by Django 4.2.2 on 2024-06-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_feature_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feature',
            name='mode',
            field=models.CharField(max_length=10),
        ),
    ]
